services:
  focuswebsite:
    image: nginx:alpine
    container_name: focuswebsite
    restart: unless-stopped
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy_net
    depends_on:
      - focuswebsite-api

  focuswebsite-api:
    build: ./api
    container_name: focuswebsite-api
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
